# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import batchflow.proto.batchflow_pb2 as batchflow__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in batchflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDataset = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/RegisterDataset',
                request_serializer=batchflow__pb2.RegisterDatasetRequest.SerializeToString,
                response_deserializer=batchflow__pb2.RegisterDatasetResponse.FromString,
                _registered_method=True)
        self.StartJob = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/StartJob',
                request_serializer=batchflow__pb2.StartJobRequest.SerializeToString,
                response_deserializer=batchflow__pb2.StartJobResponse.FromString,
                _registered_method=True)
        self.GetNextBatch = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/GetNextBatch',
                request_serializer=batchflow__pb2.GetNextBatchRequest.SerializeToString,
                response_deserializer=batchflow__pb2.GetNextBatchResponse.FromString,
                _registered_method=True)
        self.CommitBatch = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/CommitBatch',
                request_serializer=batchflow__pb2.CommitBatchRequest.SerializeToString,
                response_deserializer=batchflow__pb2.CommitBatchResponse.FromString,
                _registered_method=True)
        self.FinishJob = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/FinishJob',
                request_serializer=batchflow__pb2.FinishJobRequest.SerializeToString,
                response_deserializer=batchflow__pb2.FinishJobResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/RegisterWorker',
                request_serializer=batchflow__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=batchflow__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.HeartbeatWorker = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/HeartbeatWorker',
                request_serializer=batchflow__pb2.HeartbeatWorkerRequest.SerializeToString,
                response_deserializer=batchflow__pb2.HeartbeatWorkerResponse.FromString,
                _registered_method=True)
        self.PollMaterializeBatchTask = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/PollMaterializeBatchTask',
                request_serializer=batchflow__pb2.PollMaterializeBatchTaskRequest.SerializeToString,
                response_deserializer=batchflow__pb2.PollMaterializeBatchTaskResponse.FromString,
                _registered_method=True)
        self.CompleteMaterializeBatchTask = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/CompleteMaterializeBatchTask',
                request_serializer=batchflow__pb2.CompleteMaterializeBatchTaskRequest.SerializeToString,
                response_deserializer=batchflow__pb2.CompleteMaterializeBatchTaskResponse.FromString,
                _registered_method=True)
        self.FailMaterializeBatchTask = channel.unary_unary(
                '/batchflow.v1.CoordinatorService/FailMaterializeBatchTask',
                request_serializer=batchflow__pb2.FailMaterializeBatchTaskRequest.SerializeToString,
                response_deserializer=batchflow__pb2.FailMaterializeBatchTaskResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollMaterializeBatchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteMaterializeBatchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailMaterializeBatchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataset,
                    request_deserializer=batchflow__pb2.RegisterDatasetRequest.FromString,
                    response_serializer=batchflow__pb2.RegisterDatasetResponse.SerializeToString,
            ),
            'StartJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StartJob,
                    request_deserializer=batchflow__pb2.StartJobRequest.FromString,
                    response_serializer=batchflow__pb2.StartJobResponse.SerializeToString,
            ),
            'GetNextBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextBatch,
                    request_deserializer=batchflow__pb2.GetNextBatchRequest.FromString,
                    response_serializer=batchflow__pb2.GetNextBatchResponse.SerializeToString,
            ),
            'CommitBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitBatch,
                    request_deserializer=batchflow__pb2.CommitBatchRequest.FromString,
                    response_serializer=batchflow__pb2.CommitBatchResponse.SerializeToString,
            ),
            'FinishJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishJob,
                    request_deserializer=batchflow__pb2.FinishJobRequest.FromString,
                    response_serializer=batchflow__pb2.FinishJobResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=batchflow__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=batchflow__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'HeartbeatWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatWorker,
                    request_deserializer=batchflow__pb2.HeartbeatWorkerRequest.FromString,
                    response_serializer=batchflow__pb2.HeartbeatWorkerResponse.SerializeToString,
            ),
            'PollMaterializeBatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollMaterializeBatchTask,
                    request_deserializer=batchflow__pb2.PollMaterializeBatchTaskRequest.FromString,
                    response_serializer=batchflow__pb2.PollMaterializeBatchTaskResponse.SerializeToString,
            ),
            'CompleteMaterializeBatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteMaterializeBatchTask,
                    request_deserializer=batchflow__pb2.CompleteMaterializeBatchTaskRequest.FromString,
                    response_serializer=batchflow__pb2.CompleteMaterializeBatchTaskResponse.SerializeToString,
            ),
            'FailMaterializeBatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FailMaterializeBatchTask,
                    request_deserializer=batchflow__pb2.FailMaterializeBatchTaskRequest.FromString,
                    response_serializer=batchflow__pb2.FailMaterializeBatchTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'batchflow.v1.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('batchflow.v1.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/RegisterDataset',
            batchflow__pb2.RegisterDatasetRequest.SerializeToString,
            batchflow__pb2.RegisterDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/StartJob',
            batchflow__pb2.StartJobRequest.SerializeToString,
            batchflow__pb2.StartJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/GetNextBatch',
            batchflow__pb2.GetNextBatchRequest.SerializeToString,
            batchflow__pb2.GetNextBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/CommitBatch',
            batchflow__pb2.CommitBatchRequest.SerializeToString,
            batchflow__pb2.CommitBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/FinishJob',
            batchflow__pb2.FinishJobRequest.SerializeToString,
            batchflow__pb2.FinishJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/RegisterWorker',
            batchflow__pb2.RegisterWorkerRequest.SerializeToString,
            batchflow__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/HeartbeatWorker',
            batchflow__pb2.HeartbeatWorkerRequest.SerializeToString,
            batchflow__pb2.HeartbeatWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollMaterializeBatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/PollMaterializeBatchTask',
            batchflow__pb2.PollMaterializeBatchTaskRequest.SerializeToString,
            batchflow__pb2.PollMaterializeBatchTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteMaterializeBatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/CompleteMaterializeBatchTask',
            batchflow__pb2.CompleteMaterializeBatchTaskRequest.SerializeToString,
            batchflow__pb2.CompleteMaterializeBatchTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailMaterializeBatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.CoordinatorService/FailMaterializeBatchTask',
            batchflow__pb2.FailMaterializeBatchTaskRequest.SerializeToString,
            batchflow__pb2.FailMaterializeBatchTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchBatch = channel.unary_unary(
                '/batchflow.v1.WorkerDataService/FetchBatch',
                request_serializer=batchflow__pb2.FetchBatchRequest.SerializeToString,
                response_deserializer=batchflow__pb2.FetchBatchResponse.FromString,
                _registered_method=True)


class WorkerDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchBatch,
                    request_deserializer=batchflow__pb2.FetchBatchRequest.FromString,
                    response_serializer=batchflow__pb2.FetchBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'batchflow.v1.WorkerDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('batchflow.v1.WorkerDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchflow.v1.WorkerDataService/FetchBatch',
            batchflow__pb2.FetchBatchRequest.SerializeToString,
            batchflow__pb2.FetchBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
