defaults:
  - _self_
  - dataset: cifar10
  - topology: local
  - scheduler: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

node_id: local

logging:
  dir: batchflow/logs
  level: INFO #INFO, DEBUG, WARNING, ERROR, CRITICAL

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
  job_logging:
    level: DISABLE
  hydra_logging:
    level: DISABLE